const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

const indexSchema = {
  "@context": "http://schema.org",
  "@type": "Organization",
  name: "The Wise Duck Dev",
  url: `${siteUrl}`,
  logo: `https://${siteUrl}/images/simple_logo.png`,
  email: "wiseduckdev@gmail.com",
  member: [
    {
      "@type": "Person",
      name: "The Wise Duck Dev",
      jobTitle: "Full Stack JavaScript Developer Specialized in React",
      alumniOf: ["O'clock", "HEC Montreal"],
      email: "wiseduckdev@gmail.com",
      url: `${siteUrl}`,
      image: `https://${siteUrl}/images/metadata_profil_picture.webp`,
    },
  ],
  description:
    "Innovative full stack JS web and mobile development solutions, specializing in React.",
  brand: {
    "@type": "Brand",
    logo: `https://${siteUrl}/images/simple_logo.png`,
    sameAs: [
      "https://github.com/yannick-leguennec",
      "https://twitter.com/wiseduckdev",
    ],
  },
  knowsAbout: [
    "Web Development",
    "Mobile Web Development",
    "Systems and networks",
    "HTML5",
    "CSS3",
    "SASS",
    "JavaScript",
    "TypeScript",
    "SQL",
    "React",
    "Redux",
    "Next.js",
    "React-router-dom",
    "WordPress",
    "Node.js",
    "Express",
    "API REST",
    "Sequelize",
    "Swagger",
    "JWT",
    "Postman",
    "Test HTTP",
    "Merise Methodology",
    "PostgreSQL",
    "pgAdmin",
    "Sqitch",
    "Looping",
    "Facker",
    "Docker",
    "Git",
    "GitHub",
    "Cybersecurity",
    "Blockchain",
    "Entrepreneurship",
    "Business Creation",
    "Business Analysis",
    "Business Plan",
    "Business Model",
    "Business Development",
    "Project Management",
    "UI/UX Design",
    "Mantine UI",
    "Tailwind CSS",
    "Bootstrap",
    "Figma",
    "Canva",
    "Adobe Photoshop",
    "Adobe Express",
    "Tldraw",
    "Excalidraw",
    "Slack",
    "Trello",
    "Notion",
    "Microsoft Office",
    "Google Suite",
    "Discord",
    "Zoom",
    "Google Meet",
    "Microsoft Teams",
    "Miro",
    "GitHub Projects",
    "ChatGPT - openAI",
    "GPT-4 - openAI",
    "Claude - Anthropic",
    "Gemini - Google",
    "DALL-E 3 - openAI",
    "Midjourney",
    "Make",
    "Zapier",
  ],
  hasCredential: [
    {
      "@type": "EducationalOccupationalCredential",
      credentialCategory: "Professional",
      educationalLevel: "Professional title",
      name: "Professional title in web and web mobile development",
      recognizedBy: {
        "@type": "GovernmentOrganization",
        name: "Ministry in charge of Employment, DGEFP",
      },
    },
    {
      "@type": "EducationalOccupationalCredential",
      credentialCategory: "Certificate",
      educationalLevel: "Diploma",
      name: "HEC Montréal Diploma in Entrepreneurship and Business Creation",
      award: "First of its promotion",
      recognizedBy: {
        "@type": "EducationalOrganization",
        name: "HEC Montreal",
      },
    },
  ],
  knowsLanguage: [
    {
      "@type": "Language",
      name: "French",
    },
    {
      "@type": "Language",
      name: "English",
    },
    {
      "@type": "Language",
      name: "Spanish",
    },
  ],
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "customer support",
    email: "wiseduckdev@gmail.com",
  },
};

export default indexSchema;
