const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

const indexSchema = {
  "@context": "http://schema.org",
  "@type": "Person",
  name: "The Wise Duck Dev",
  jobTitle: "Full Stack JavaScript Developer Specialized in React",
  email: "wiseduckdev@gmail.com",
  url: `${siteUrl}`,
  image: `https://${siteUrl}/images/main_logo1.png`,
  alumniOf: ["O'clock", "HEC Montreal"],
  memberOf: {
    "@type": "Organization",
    name: "The Wise Duck Dev",
    description:
      "Innovative full stack JS web and mobile development solutions, specializing in React.",
    url: `${siteUrl}`,
    logo: `https://${siteUrl}/images/main_logo1.png`,
    sameAs: ["https://github.com/yannick-leguennec"],
  },
  knowsAbout: [
    "Web Development",
    "Mobile Web Development",
    "Systems and networks",
    "HTML5",
    "CSS3",
    "SASS",
    "JavaScript",
    "TypeScript",
    "SQL",
    "React",
    "Redux",
    "Next.js",
    "React-router-dom",
    "WordPress",
    "Node.js",
    "Express",
    "API REST",
    "Sequelize",
    "Swagger",
    "JWT",
    "Postman",
    "Test HTTP",
    "Merise Methodology",
    "PostgreSQL",
    "pgAdmin",
    "Sqitch",
    "Looping",
    "Facker",
    "Docker",
    "Git",
    "GitHub",
    "Cybersecurity",
    "Blockchain",
    "Entrepreneurship",
    "Business Creation",
    "Business Analysis",
    "Business Plan",
    "Business Model",
    "Business Development",
    "Project Management",
    "UI/UX Design",
    "Mantine UI",
    "Tailwind CSS",
    "Bootstrap",
    "Figma",
    "Canva",
    "Adobe Photoshop",
    "Adobe Express",
    "Tldraw",
    "Excalidraw",
    "Slack",
    "Trello",
    "Notion",
    "Microsoft Office",
    "Google Suite",
    "Discord",
    "Zoom",
    "Google Meet",
    "Microsoft Teams",
    "Miro",
    "GitHub Projects",
    "ChatGPT - openAI",
    "GPT-4 - openAI",
    "Claude - Anthropic",
    "Gemini - Google",
    "DALL-E 3 - openAI",
    "Midjourney",
    "Make",
    "Zapier",
  ],
  knowsLanguage: ["French", "English", "Spanish"],
  hasCredential: [
    {
      "@type": "EducationalOccupationalCredential",
      name: "Professional title in web and web mobile development",
      educationalLevel: "Professional title",
      credentialCategory: "Professional",
      recognizedBy: {
        "@type": "GovernmentOrganization",
        name: "Ministry in charge of Employment, DGEFP",
      },
    },
    {
      "@type": "EducationalOccupationalCredential",
      name: "HEC Montréal Diploma in Entrepreneurship and Business Creation",
      educationalLevel: "Diploma",
      credentialCategory: "Certificate",
      award: "First of its promotion",
      recognizedBy: {
        "@type": "EducationalOrganization",
        name: "HEC Montreal",
      },
    },
  ],
};

export default indexSchema;
